id: P7DD2F26A
initial_creation_type: ocr
source_metadata:
  volumes:
    389ba4eceab04a0fb5adfb964a4984d6:
      base_file: v074.txt
      image_group_id: I1PD95919
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་རྣམ་པར་གཏན་ལ་དབབ་པ་བསྡུ་བ།
      total_pages: 1618
      volume_number: 74
